# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish $(buildConfiguration)'

- task: AzureFileCopy@3
  inputs:
    sourcePath: '$(Build.SourcesDirectory)/Site'
    azureSubscription: conn
    destination: azureBlob
    storage: azurecomstats
    containerName: "$web"

- task: PublishBuildArtifacts@1
